### ISSUE TITLE
Use markdown-toc instead of marked-toc

### ISSUE THREAD

**Issue by Ilshidur** [marcells/bloggy-summary#1]
marked-toc is deprecated (and also vulnerable to XSS injections).
Use [markdown-toc](https://github.com/jonschlinkert/markdown-toc) instead.

I can open a pull request if necessary.

**Comment by marcells** [comment]
Hi, feel free to do this. Thank you!

**Comment by Ilshidur** [comment]
Submitted issue to the wrong repo. Closing ...

([the actual PR link](https://github.com/marcells/bloggy-marked-toc/pull/1))
